### ISSUE TITLE
MacOS - unable to locate Blender renderer within binary download

### ISSUE THREAD

**Issue by buzzdev** [laurent-clouet/sheepit-client#182] opened 2019-05-02 21:08 UTC
**Client version**: 5.1292.2977
**OS**: MacOS 10.14.3
**JDK version**: java 11.0.3 2019-04-16 LTS
**JRE version**: Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)

**Debug log**:
```
02-05 23:01:37 (debug) Saved: '/Users/martin/Desktop/SHTEMP/sheepit/1_0340.png'
02-05 23:01:37 (debug)  Time: 00:00.39 (Saving: 00:00.22)
02-05 23:01:37 (debug) Blender quit
02-05 23:01:37 (debug) end of rendering
02-05 23:01:37 (debug) Job::render pictureFilename: '/Users/martin/Desktop/SHTEMP/sheepit/1_0340.png'
02-05 23:01:37 (debug) will validate Job (numFrame '0340' sceneMD5 'd8b01c8656cca48b8a22bc7048783fe9' rendererMD5 '9dc4d1d68f54deefe3fcda9a3babd80f' ID '1' pictureFilename '/Users/martin/Desktop/SHTEMP/sheepit/1_0340.png' jobPath 'compute-method.blend' gpu true name 'Can Blender be launched?' extras '' updateRenderingStatusMethod 'remainingtime' render com.sheepit.client.RenderProcess@7b5eedfe)
02-05 23:01:37 (debug) Server::HTTPSendFile(https://client.sheepit-renderfarm.com/server/send_frame.php?job=1&frame=0340&rendertime=1&memoryused=8500&extras=&cores=8,/Users/martin/Desktop/SHTEMP/sheepit/1_0340.png)
02-05 23:01:39 (debug) Server::HTTPRequest url(https://client.sheepit-renderfarm.com/ajax.php?action=webclient_get_last_render_frame_ui&type=raw)
02-05 23:01:41 (debug) Server::requestJob
02-05 23:01:42 (debug) Server::HTTPRequest url(https://client.sheepit-renderfarm.com/server/request_job.php?computemethod=1&cpu_cores=8&ram_max=16777216&rendertime_max=0)
02-05 23:01:43 (debug) Server::handleFileMD5DeleteDocument delete old file /Users/martin/Desktop/SHTEMP/sheepit/d8b01c8656cca48b8a22bc7048783fe9

**02-05 23:01:43 (debug) Got work to do id: 524147 frame: 0818
02-05 23:01:49 (error) Client::work job preparation failed (renderer file '/Users/martin/Desktop/SHTEMP/sheepit/7c6501cb08c6be481fe701ff90c607ea/Blender/blender.app/Contents/MacOS/blender' does not exist), cleaning directory in hope to recover
02-05 23:01:50 (debug) Sending error to server (type: MISSING_RENDERER)**
```

**Comment by buzzdev** [comment] 2019-05-03 16:44
I've checked the referenced issue #153 but couldn't find a single similarity.

**Comment by MCOfficer** [comment] 2019-05-03 17:53
As far as we know, most Py_Initialize issues were caused by something removing the renderer before the process could start. As a workaround, clou made the client clean the binary folder, which is what you're seeing in the second-to-last line.

**Comment by buzzdev** [comment] 2019-05-03 21:18
Today i’ve tried on Mac again and all worked fine. It rendered some projects without any problem.
Perhaps it was related to that particular project and the downloaded binaries? Possibly corrupted?

**Comment by laurent-clouet** [comment] 2019-05-05 10:47
I'll add some debug log for the next time because it's an issue of we don't know the root cause.
We have a workarround (to clean the cache) but it's not a proper fix.

Did you launch multiple client at the same or only one ?

**Comment by buzzdev** [comment] 2019-05-05 19:49
Only one at that time. On the second try, on next day, i left one running on a linux PC and tried the macos again and it worked. But as i said, it loaded different project already.
I tend to think it was that exact project related. The error message says that it cannot launch renderer, because it was missing in the binary download.

`02-05 23:01:49 (error) Client::work job preparation failed (renderer file '/Users/martin/Desktop/SHTEMP/sheepit/7c6501cb08c6be481fe701ff90c607ea/Blender/blender.app/Contents/MacOS/blender' does not exist), cleaning directory in hope to recover`

The missing file just wasn't there, delivered at the download time.

**Comment by rivadav** [comment] 2019-06-26 13:23
I've encountered the same issue. However, it went smoothly with another project.

**Comment by LasseRB** [comment] 2019-07-05 09:26
Same issue. Also MAC. 
I've noticed that - unlike the other projects I have rendered for people - my files get named `.DS_Store`, not the name of the project. (I can tell If I try and extract the archive).

**Comment by laurent-clouet** [comment] 2019-07-25 07:48
It was an issue on the blender OSX archive build.
It should be fixed now.

**Closed by laurent-clouet** 2019-07-25 07:48 UTC
