### ISSUE TITLE
sheepit ignore amp gpu on ubuntu

### ISSUE THREAD

**Issue by osamaemad072** [laurent-clouet/sheepit-client#213] opened 2020-04-17 15:46 UTC
![Screenshot from 2020-04-17 17-39-03](https://user-images.githubusercontent.com/51472250/79587816-5d4cf200-80d3-11ea-81f9-a1a2ce0e5983.png)
sheepit client doesn't recognize my gpu ,

i've installed opencl and the pro amd driver and the gpu works fine with blender and i use it for render in blender

gpu... amd rx580

cpu ryzen 5 2600x

ubuntu 18.04

what's the solution please ?
is amd gpu supported in sheepit ?

**Comment by MCOfficer** [comment] 2020-04-17 18:08
duplicate of #165

**Closed** 2020-04-23 23:18 UTC
