### ISSUE TITLE
Client has to re-download renderer for every new project

### ISSUE THREAD

**Issue by Creator13** [laurent-clouet/sheepit-client#37] opened 2015-08-28 15:49 UTC
I don't know if this was intended, but since a while, the client re-downloads the renderer for every new project, and also every time the client is restarted. To me, this seems like a waste of time and bandwidth. Why not save every renderer once it's needed, and eventually update one or two. This could also be made into a setting, so that the user can choose for himself whether he wants it or not, or to change how many renderers are stored to save disk space (and avoid flooding the user's hard drive).

**Comment by laurent-clouet** [comment] 2015-09-01 16:49
It's not intended and i can't reproduce it.
Are you using the -cache-dir option (or selecting the cache dir in the ui) ? without this it will re-download everything everytime

**Comment by Creator13** [comment] 2015-09-07 13:39
Using a user-defined directory does indeed solve the problem. Could you explain to me where the client puts the files when there is no folder specified? I'm having a hard time digging through the code to find that, and I'm pretty sure the problem lies within this folder. If it's a tmp folder, it will be removed every time, and that would explain this problem. If this is the case, my suggestion is that the client creates a standard folder (in AppData for Windows for example, and the Mac and Linux equivalents) in which it stores the files.

**Comment by Ghoughpteighbteau** [comment] 2015-09-10 22:23
so thaaaaat's what's going on. @laurent-clouet would you consider adding this bit of info on the FAQ? It's somewhat unexpected behavior.

**Comment by Creator13** [comment] 2015-09-10 22:28
It's a bug, It's going to be fixed once I figure out how. Or if someone else is faster than me...

**Comment by Ghoughpteighbteau** [comment] 2015-09-10 23:33
ah. Yah I just noticed it's discarding the cache dir even after I specify it. :\

**Comment by Creator13** [comment] 2015-09-11 06:19
Hmm.. That's also interesting. Are you sure it really deletes the whole folder? For me, it only deletes the folders it creates, but not the zip files. What system are you using?

**Comment by Ghoughpteighbteau** [comment] 2015-09-11 18:35
Here's the command I run:

`optirun java -jar ./sheepit-client-3.182.2281.jar -cache-dir ~/.sheepit/gpu -compute-method GPU -gpu CUDA_0 -cores 1 -ui text -login manghoti -password ****`

Here's my /tmp directory right now.

![caching in /tmp?!](http://i.imgur.com/cxGk8zV.png)

so it's ignoring the command, *BUT*. it IS putting data in ~/.sheepit/gpu ! So it's not ignoring the command.

Frankly I think the option isn't being applied consistently.

**Comment by Creator13** [comment] 2015-09-14 20:45
The code for this is messy. Like I said earlier, I would suggest to store the files in an AppData-like folder, instead of tmp. Of course with the possibility for a user-defined directory as well. I don't really see the point in the whole folder being cleared, so @laurent-clouet could you please explain why you do that? The binaries might need to be checked, but not necessarily deleted (I think). As for the projects, they could be stored in a separate folder.

Also, I suppose the deletion of directories while the zips are kept (when the hash is correct) is also for security purposes?

**Comment by Ghoughpteighbteau** [comment] 2015-09-14 21:32
I'm not sure if security is the right word.

**Comment by laurent-clouet** [comment] 2015-09-21 17:42
The original goal was to store nothing permanently on the render machine, that's why the /tmp is used.
But these days more and more renderer are using sheepit daily so i agree the cache dir should be move to a more permanently directory.
Now it should have two cache dir, one for the blender binary (somewhere in the home) and one for the project (/tmp is still a good place).

When a user specify a cache-dir everything should go in it but when nothing is specify it should split in 2 directories. That's the goal of Configuration.setCacheDir and Configuration.setStorageDir methods, and yes i agree the name are not really great.
Those directory should be renamed or at least some comment should be added.

@Ghoughpteighbteau i'll try to reproduce your issue because i should not happen. It will fall back to /tmp if the cache directory specified does not exist. In this case i think it should exit and not silently go to /tmp/

**Comment by Creator13** [comment] 2015-09-21 19:43
The naming should be consistent: right now there is a cacheDir and workingDir that refer to the same thing.

I suggest we name the temporary directory `projectDir` or `cacheDir` and either keep the name `storageDir`, or if it is sure it will only be used for the binaries, then `binaryDir`.  I'm working on this right now.

**Comment by laurent-clouet** [comment] 2015-09-21 19:54
They could be the same because the "workingDir" is included in the "cacheDir".

For the names, binaryDir and projectDir sound good. 
But if you do that you need to a system who always will create these binaryDir on the filesystem. You also need a way to specify that you don't want to create the directory (to actually leave to trace on the renderer machine).

**Comment by bestknighter** [comment] 2016-09-16 19:37
I'm having the same issue. Even though I already have Blender installed, every time I run the standalone client, it re-downloads the renderer. I've already setup a folder for it and this keeps happening. Right now I have three renderers downloaded, beyond the Blender itself.

I'm in Windows 10 using the standalone client.

**Comment by supersammy7000** [comment] 2016-09-17 01:33
@bestknighter That is how it is supposed to work. The issue here is that every new project the renderer is being redownloaded not just when they start up the client. You are not required to have blender installed so it downloads blender every time you startup the client and gets the correct version for the project that needs to be rendered.

**Comment by bestknighter** [comment] 2016-09-21 02:56
Wouldn't it be better if there were a directory with all the downloaded renderers, re-use them as much as needed, and then delete if a certain renderer isn't used for longer than a set value (that can be defaulted in the settings as 1 month, for example)? I also believe that if the user has blender installed, it could be referenced as one of the renderers available in the machine, but an undeletable one.

**Comment by supersammy7000** [comment] 2016-09-21 03:05
Yes it would be better if it saved but it doesn't yet. I think it is
planned. I don't think it is a good idea to use the version of blender you
have installed. Not every machine running Sheepit has blender installed
that is why it is downloaded and it is downloaded because you set the
specific version of blender you want. It is usually just the latest but
there are different versions incase some feature gets broken or unsupported
on certain versions. I would also like to remind you that this issue is not
the feature request for the issue your talking about. You can open up an
issue for it if you please but this is for a bug that required the renderer
to download again for every project rendered not just on start up.

**Comment by bestknighter** [comment] 2016-09-21 03:35
Oh, yeah, sorry, I forgot about that. Tomorrow I'll open a new issue about that and explaining carefully about my idea.

**Comment by Ghoughpteighbteau** [comment] 2016-09-21 17:05
it isn't?

Oh you mean using the locally installed blender.

Yah bestknighter that's a bad idea. How can you be sure the local blender installation isn't configured in a way that might cause frames to render differently? An example: You could have your blender installation set to permissive to scripts. A blend files submitted for rendering arn't supposed to have scripts, but they do get passed anyway because clients default ignore them. If your local client doesn't, then you will render frames differently than others. 

There could be other issues as well. Downloading an isolated copy guarantees no problems.

Though, there really is no reason why we should have to redownload them every time we start a session.

**Comment by supersammy7000** [comment] 2016-09-21 17:47
I believe that caching the renderer is on the todo list.

**Comment by bestknighter** [comment] 2016-09-22 01:52
@Ghoughpteighbteau got it now. I didn't know that those configurations could affect the render.

**Comment by laurent-clouet** [comment] 2017-04-30 20:57
It's fixed on fbec2ee36ec1f63e108388c1782a44510551befa
There is a semi-permanent directory in /tmp to store blender binary archive.

**Closed by laurent-clouet** 2017-04-30 20:57 UTC
Labels: bug
